<?php

// PAGE ID
define("PAGE_HOME", 1);
define("PAGE_CONNECTION", 2);
define("PAGE_PROFILE", 3);
define("PAGE_MODIFY_PROFILE", 4);
define("PAGE_REGISTER", 5);
define("PAGE_BASKET", 6);
define("PAGE_PRODUCTS", 7);
define("PAGE_FAVORITE", 8);
define("PAGE_ABOUTUS", 9);
define("PAGE_CONDITIONS", 10);
define("PAGE_CONTACT", 11);
define("PAGE_ADMIN_CANDIES", 12);
define("PAGE_ADMIN_USERS", 13);
define("PAGE_ADMIN_ADD_CANDIES", 14);
define("PAGE_ADMIN_MODIFY_CANDIES", 15);
define("PAGE_ADMIN_DELETE_CANDIES", 16);
define("PAGE_ADMIN_DELETE_CANDIES_COMFIRM", 17);
define("PAGE_ADMIN_CATEGORIES", 18);
define("PAGE_ADMIN_ADD_CATEGORIES", 19);
define("PAGE_ADMIN_MODIFY_CATEGORIES", 20);
define("PAGE_ADMIN_DELETE_CATEGORIES", 21);
define("PAGE_ADMIN_DELETE_CATEGORIES_COMFIRM", 22);

// ACTION ID
define("CONNECTION", 100);
define("DISCONNECTION", 101);
define("MODIFICATION_OF_PROFILE", 102);
define("ADD_FAVORITES", 103);
define("FILTER_PRODUCTS", 104);
define("ADD_CANDY", 105);
define("MODIFY_CANDY", 106);
define("DELETE_CANDY", 107);
define("ADD_CATEGORY", 108);
define("DELETE_CATEGORY", 109);
